# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shiv Ratan Sinha
title: Master's student at New York University
email: sinha.shivratan@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  srsinha
leetcode_username: srsinha
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: shiv.sinha
linkedin_username: shiv-ratan-sinha
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Designs
  icon: fas fa-box-archive
  url: https://drive.google.com/drive/folders/0B-ROXwFsebJbQUpfRE02bWZWSFE

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-65GVZMJ6MW"
google_analytics: "G-65GVZMJ6MW"

# About Section
# about_title: About Me
about_profile_image: images/profileSRS.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Shiv and I am a 2nd year Master's student at NYU-Courant. I have experience working as a SDE at <mark>Adobe</mark> and SDE intern at <mark>Tiktok</mark>.

  I also enjoy: <mark>  Designing</mark> and <mark>Sketching</mark>

content:  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tiktok, Bytedance
        link: tiktok.com
        # link_text: boringcompany.com
        sub_title: Software Developer Intern
        caption: 23'May 2022 - 19'August 2022
        quote: >
          Developers Portal Tiktok
        description: | # this will include new lines to allow paragraphs
            - Owned the design and development of history management feature in the Tiktok developers portal; in Go.
            - Extra project; developed an optimal algorithm for scheduling meeting amongst people around globe; in Python.
      
      - layout: left
        title: New York University
        link: nyu.com
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: May 2021 - June 2022
        quote: >
          Containerizing web-scrapping
        description: | # this will include new lines to allow paragraphs
            - Parallelized Python data crawling using multiple containers, highly appreciated by Professor Raveesh Mayya, NYU-Stern, for doubling scrapping rate with lesser resource utilisation using containers.
            - Data extraction and analysis of large online secondary market using Python multiprocessing and RapidMiner.
            - Ported the setup to GCP for efficient management and processing.


      - layout: left
        title: Adobe
        link: adobe.com
        # link_text: boringcompany.com
        sub_title: Computer Scientist
        caption: 01'Jan 2021 - 01'Jan 2022
        quote: >
          Also explored management, showed leadership and customer support.
        description: | # this will include new lines to allow paragraphs
            - Owned entire development of Integrations of Adobe Experience Manager and Target/Analytics, using Java; also managed work of 3 fellow developers.
            - Timely resolved high level of customer issues by managing Kubernetes clusters for AEM as cloudservice.

      - layout: left
        title: Adobe
        link: adobe.com
        # link_text: boringcompany.com
        sub_title: Senior Member of Technical Staff
        caption: 01'Jan 2021 - 01'Jan 2022
        quote: >
          AEM multi-channel and new project ownership
        description: | # this will include new lines to allow paragraphs
            - Led and accomplished smooth transfer of ownership of ’Integrations’ (10 code repositories). Within 5 months of ownership, the product was successfully made cloud-native, leading to the on-boarding of 10+ new customers.
            - Contributed to the development of multi-channel interactive forms in AEM Forms by developing the web and print-based channel using Java and JavaScript.

      - layout: left
        title: Adobe
        link: adobe.com
        # link_text: boringcompany.com
        sub_title: Member of Technical Staff
        caption: 01'Jan 2021 - 01'Jan 2022
        quote: >
          Rest APIs and CCR UI
        description: | # this will include new lines to allow paragraphs
            - Oversaw and managed development of ’Agent UI’ product using AngularJS; improved performance by 15% (for client Deutsche Bank).
            - Developed RESTful APIs, UI in AngularJS and hosted the NLP based contextualization engine-Manthan on a multi-cloud container platform-Ethos; product was showcased in Adobe Tech Summit 2017.

      - layout: left
        title: Intap Labs Pvt Ltd, India
        link: helloenglish.com
        # link_text: boringcompany.com
        sub_title: Technical Intern
        caption: May 2015 - July 2015
        quote: >
          UI/UX and NLP based
        description: | # this will include new lines to allow paragraphs
            - Redesigned UI of Hello English app’s home-page and user-profile page using Proto.io. Acknowledged directly by the CEO for the new Material Design based UI.
            - Contributed to NLP-based text readability feature: send news articles to users based on their reading abilities.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New York University
        caption: 2021 - 2022, GPA 3.96
        sub_title: MS Computer Science
        link: nyu.edu
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at NYU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I grabbed the opportunities to work as a Research Assistant, as a CTO-developer as well as a Grader and a Tutor.

      - layout: left
        title: Malaviya National Institute of Technology Jaipur 
        caption: 2012 - 2016, GPA 8.52
        sub_title: B.Tech Computer Science
        link: mnit.ac.in
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at MNIT I developed my passion for algorithms and coding. While exploring the vast field of Computer Science I was also actively involved in various campus activities and responsibilities. I lead the Technical Society there in my 3rd year of undergrad and was also part of the college dance group in my early years of college.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Multi-modal multi-environment performance comparison on GCP
        link: NYU, Spring 2022
        # link_text: NYU, Spring 2022
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Where do I deploy my particular ML application?
        description: | # this will include new lines to allow paragraphs
          In this project we tried to compare three environments i.e., the bare Virtual Machine, Docker running inside the Virtual Machine, and Singularity running inside the Virtual Machine on two different workloads i.e., an MNIST digit classifier using Convolutional Neural Network and a Sentiment Analyzer using Recurrent Neural Network. We used the same underlying hardware and ran all the workloads using a GPU-enabled Virtual Machine inside the Google Cloud Platform to better compare the metrics and understand the implication of the change of metrics in different environments on the performance of the application.

      - layout: top-middle
        title: Spotify Playlist Song Recommendation System using Spark
        link: NYU, Spring 2022
        # link_text: NYU, Spring 2022
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Song recommendations that are fresh to the ears and fit your listening habits.
        description: | # this will include new lines to allow paragraphs
          It is important for a recommendation system to minimize the user’s effort for providing feedback and to maximize the user’s satisfaction by playing the appropriate song at the right time. In this project, we leveraged the existing user’s song organization data alongwith the track’s metadata to analyze and recommend new tracks to the listener.

      - layout: top-middle
        title: Movie Genre Prediction from Posters
        link: NYU, Fall 2021
        # link_text: NYU, Fall 2021
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A good movie poster can convey a film's theme and genre to a wider audience,
        description: | # this will include new lines to allow paragraphs
          Here we examined not only the visual aspects of the poster but also analyzed the textual information, to see if it can reinforce the model. In combination with textual learning, ResNet50 was able to predict movie poster genres fairly accurately. This suggests that the visual elements included in movie posters of a given genre are relatively consistent.

      - layout: top-middle
        title: Predicting Road Repair Timelines Using Traffic Data
        link: NYU, Fall 2021
        # link_text: NYU, Fall 2021
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data Science can play a big role in getting insights from uncharted territories.
        description: | # this will include new lines to allow paragraphs
           Through this project, we investigated the predictive correlation and causation between (1) Average Daily Traffic of an area and (2) Number of reports of potholes and road damages in the same area.

      - layout: top-middle
        title: CyberTongue
        link: MNIT, 2015
        # link_text: MNIT, 2015
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Quora was popular at that time, so something inspired by that?
        description: | # this will include new lines to allow paragraphs
           It was a team of 2 and we developed a Q&A portal using PHP and MySQL. We were inspired by the success of Quora and got inspired to create something similar to that; received AA in the project.

      - layout: top-middle
        title: DDoS Detection-Mitigation
        link: MNIT, 2015-16
        # link_text: MNIT, 2015-16
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The then existing mitigation techniques failed to operate when the server is under massive DDoS attack.
        description: | # this will include new lines to allow paragraphs
           The proposed technique ensures the availability of enough resources during massive DDoS attacks for the existing DDoS mitigation techniques. This is done by blocking the attack traffic for certain time and making the resources available to the DDoS mitigation tools.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests software engineering some of my other interests and hobbies are:
      - Sketching
      - Trekking
      - Dancing

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
